config/routes.rb
Rails.application.routes.draw do
  resources :skills
  devise_for :users, module: "users"
  resources :skills
  resources :users do
    scope module: :users do
      resources :skills
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]

  root 'pages#index'

  get '*path' => redirect('/')

  post 'skills/search'
  post 'users/search'
  post 'skills/endorseskill'
  post 'users/endorseuser'
  
	

end

app/models/user.rb
class User < ActiveRecord::Base
  include Searchable

  rolify
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :omniauthable
  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills
  has_many :identities, dependent: :destroy

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def add_skill(skill)
    user_skills.create(skill_id: skill.id)
  end

  def remove_skill(skill)
    user_skills.find_by(skill_id: skill.id).destroy
  end

  def has_skill?(skill)
    skills.include?(skill)
  end

  def is_admin?
    has_role? :admin
  end

  def is_assessor?(skill)
    has_role? :assessor, skill
  end

  def is_assessor_of_any?
    roles.any? do |role|
      role[:name] == "assessor" && role[:resource_type] == "Skill"
    end
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
   before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    render :text => request.env['rack.auth'].inspect
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :authenticate_user!
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
      }
  end

  [:github, :facebook].each do |provider|
    provides_callback_for provider
  end

  #def after_sign_in_path_for(resource)
    #if resource.email_verified?
      #super resource
    #else
      #finish_signup_path(resource)
    #end
  #end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_filter :configure_sign_up_params, only: [:create]
  # before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    # Grant admin priviledges if this is the only account
    if User.count == 0
      @user.add_role :admin
    end
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
    render :text => request.env['rack.auth'].inspect
    # Grant admin priviledges if this is the only account
    if User.count == 1
      @user.add_role :admin
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/settings_controller.rb
class Users::SkillsController < ApplicationController
  # GET /user/skills
  # GET /user/skills.json
  def index
  end
end

app/controllers/users/skills_controller.rb
class Users::SkillsController < ApplicationController
  before_action :set_user_skill, only: [:show, :edit, :update, :destroy]
  before_action :skip_authorization

  # GET /user/skills
  # GET /user/skills.json
  def index
    @user_skills = current_user.skills
  end

  # GET /user/skills/1
  # GET /user/skills/1.json
  def show
  end

  # GET /user/skills/new
  def new
    @user_skill = UserSkill.new
  end

  # GET /user/skills/1/edit
  def edit
  end

  # POST /user/skills
  # POST /user/skills.json
  def create
      #byebug
    
    params[:user_skill][:user_id] = current_user.id if current_user
    @user_skill = UserSkill.new(user_skill_params)

    respond_to do |format|
      if @user_skill.save
        format.html { redirect_to current_user, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @user_skill }
      else
        format.html { render :new }
        format.json { render json: @useuser_skill_paramsr_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/skills/1
  # PATCH/PUT /user/skills/1.json
  def update
    respond_to do |format|
      if @user_skill.update(user_skill_params)
        format.html { redirect_to '/user_skuser_skill_paramsills', notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_skill }
      else
        format.html { render :edit }
        format.json { render json: @user_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/skills/1
  # DELETE /user/skills/1.json
  def destroy
    @user_skill.destroy
    respond_to do |format|
      format.html { redirect_to user_skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_skill
      @user_skill = current_user.skills.find(params[:user_skill][:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_skill_params
       
      accessible = [ :user_id, :skill_id, :id ] # extend with your own params
      params.fetch(:user_skill, {}).permit(accessible)
    end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/skills_helper.rb
module User::SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_skills_form.html.haml
= form.select :skill_ids, Skill.all.collect {|x| [x.name, x.id]}, {}, :multiple => true, :size =>10

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :email
    %br/
    = f.text_field :email
  = render partial: "add_skills_form", locals: { form: f }
  .actions
    = f.submit

app/views/users/_form1.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/users/_roles.html.haml
-if @user == current_user
  -if current_user.is_admin?
    %center Admin
  %br/
  -if current_user.is_assessor_of_any?
    %p You are authorized to assess users in the following skills:
    %ul
    -GetUserAssessibleSkills.call(current_user).each do  |skill|
      %li= link_to skill.name, skill

app/views/users/_skills.html.haml
.skills
  %ul.skills
    = render @skills

app/views/users/add_skills.html.haml
= form_for @user do |f|
  .actions
    = f.submit
  = render partial: 'add_skills_form', locals: { form: f }
= link_to 'Back', users_path

app/views/users/edit.html.haml
%h2 Editing User
= render 'form'
= link_to 'Add Skill', add_skills_path(@user)
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/finish_signup.html.haml
#add-email.container
  %h2 Add Email
  = form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f|
    - if @show_errors && current_user.errors.any?
      #error_explanation
        - current_user.errors.full_messages.each do |msg|
          = msg
          %br/
    .form-group
      = f.label :email
      .controls
        = f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com'
        %p.help-block Please confirm your email address. No spam.
    .actions
      = f.submit 'Continue', :class => 'btn btn-primary'

app/views/users/index.html.haml
%body
  %h1 Users
  = form_tag  :controller => :users, :action => :search, method: 'post'do
    = text_field_tag :search, params[:search]
    = submit_tag "Search", name: nil
  
    %table.container
      %thead
        %tr
          %th{:colspan => "3"}
  
    %table.container
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.name, user
            - if current_user.is_admin?
              - if current_user.is_admin?
                %td= link_to 'Edit', edit_user_path(user) if current_user.is_admin?
                %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
                %td= link_to 'Add Skills', new_user_skill_path(user)
  :css
    input[type="submit"] {

    background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;
    overflow: hidden;
    outline:none;
    width= 30;
    height= 30;
    }

    @import url(http://fonts.googleapis.com/css?family=Open+Sans:300,400,700);



    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #FB667A;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }

app/views/users/new.html.haml
%h2 New User
= render 'form'
= link_to 'Back', users_path

app/views/users/search_user.html.haml
%p#notice= notice
%p
%center
  %font{:size => "5"}
    %strong
      = @user.name
%table{:style => "width:100%"}
  %tr
    %th
      %p
        %strong Skill
    %th
      %p
        %strong Category
    %th
      %p
        %strong Competence
  - @skills.each do |skill|
    %tr
      %td
        = skill.name
      %td
        = skill.category
      %td
        = UserSkill.find_by(skill_id: skill.id , user_id: @user.id).competence
      %td
        - if current_user.has_role? :assessor, skill

          %form#tfnewsearch{:action => "/users/endorseuser?endorseUser=#{@user.id}&endorseSkill=#{skill.id}", :method => "post"}
            %input#button{:type => "image", :height => "30", :src => "#{asset_path( 'endorse.gif' )}", :width => "30"}


  = link_to 'Back', users_path 
  
  
  
  
  
  :css




    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #4DC3FA;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }

app/views/users/show.html.haml
%center
  %font{:size => "5"}
    %strong
      = @user.name
%br/
= render 'roles', :locals => {:user => @user}
%br/
%table{:style => "width:100%"}
  %tr
    %th
      %p
        %strong Skill
    %th
      %p
        %strong Category
    %th
      %p
        %strong Competence
  - @user_skills.each do |user_skill|
    %tr
      %td
        = user_skill.skill.name
      %td
        = user_skill.skill.category
      %td
        = user_skill.competence

%br/
%br/
-if current_user == @user
  =link_to "Add skills", new_user_skill_path(current_user), class: "btn btn-primary"


:css




    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #4DC3FA;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }