config/routes.rb
Rails.application.routes.draw do
  resources :skills
  devise_for :users, module: "users"
  resources :skills
  resources :users do
    scope module: :users do
      resources :skills
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]

  root 'pages#index'

  get '*path' => redirect('/')

  post 'skills/search'
  post 'users/search'
  post 'skills/endorseskill'
  post 'users/endorseuser'
  
	

end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
  validates_uniqueness_of :user_id, scope: :skill_id
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
  before_action :set_user_skill, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  # skip_callback(:search ,:before, :set_user_skill)

  # GET /user_skills
  # GET /user_skills.json
  def index
    @user_skills = UserSkill.all
  end

  # GET /user_skills/1
  # GET /user_skills/1.json
  def show
  end

  # GET /user_skills/new
  def new
    @user_skill = UserSkill.new
  end

  # GET /user_skills/1/edit
  def edit
  end







  # POST /user_skills
  # POST /user_skills.json
  def create
    @user_skill = UserSkill.new(user_skill_params)

    respond_to do |format|
      if @user_skill.save
        format.html { redirect_to @user_skill, notice: 'User skill was successfully created.' }
        format.json { render :show, status: :created, location: @user_skill }
      else
        format.html { render :new }
        format.json { render json: @user_skill.errors, status: :unprocessable_entity }
        endskip_before_filter :verify_authenticity_token
      end
    end
  end

    # PATCH/PUT /user_skills/1
    # PATCH/PUT /user_skills/1.json
    def update
      respond_to do |format|
        if @user_skill.update(user_skill_params)
          format.html { redirect_to @user_skill, notice: 'User skill was successfully updated.' }
          format.json { render :show, status: :ok, location: @user_skill }
        else
          format.html { render :edit }
          format.json { render json: @user_skill.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /user_skills/1
    # DELETE /user_skills/1.json
    def destroy
      @user_skill.destroy
      respond_to do |format|
        format.html { redirect_to user_skills_url, notice: 'User skill was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private


    # Use callbacks to share common setup or constraints between actions.
    def set_user_skill
      if params[:id]!="search"
        @user_skill = UserSkill.find(params[:id])
      end
    end

    skip_before_filter :verify_authenticity_token
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_skill_params
      params.require(:user_skill).permit(:competence)
    end




  end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/views/user_skills/edit.html.haml
%h2 Editing User Skill
= render 'form'
= link_to 'Show', @user_skill
|
= link_to 'Back', user_skills_path

app/views/user_skills/index.html.haml
%h2 Comptrac
%head
  %title Search Box Example 1
  %meta{:content => "NOINDEX, NOFOLLOW", :name => "ROBOTS"}/
  / CSS styles for standard search box
  :css
    #tfheader{
    	
    }
    #tfnewsearch{
    	float:right;
    	padding:20px;
    }
    .tftextinput{
    	width: 500px;  height: 30px; position: absolute;
    right: 32%;  top: 30%;  
    	padding: 5px 15px;
    	font-family: Arial, Helvetica, sans-serif;
    	font-size:14px;
    	border:1px solid #0076a3; border-right:0px;
    	border-top-left-radius: 5px 5px;
    	border-bottom-left-radius: 5px 5px;

	
    }
    #tfselect{
    	width: 100px;  height: 40px; position: absolute;
    right: 74%;  top: 30%;  
    	padding: 5px 15px;
    	font-family: Arial, Helvetica, sans-serif;
    	font-size:14px;
    	border:1px solid #0076a3; border-right:0px;
    	border-top-left-radius: 5px 5px;
    	border-bottom-left-radius: 5px 5px;

	
    }

    .tfbutton {
    	height: 42px;  position: absolute;  right: 23%;  top: 30%; 
    	padding: 5px 15px;
    	font-family: Arial, Helvetica, sans-serif;
    	font-size:25px;
    	outline: none;
    	cursor: pointer;
    	text-align: center;
    	text-decoration: none;
    	color: #ffffff;
    	border: solid 1px #0076a3; border-right:0px;
    	background: #0095cd;
    	background: -webkit-gradient(linear, left top, left bottom, from(#00adee), to(#0078a5));
    	background: -moz-linear-gradient(top,  #00adee,  #0078a5);
    	border-top-right-radius: 5px 5px;
    	border-bottom-right-radius: 5px 5px;
    }
    .tfbutton:hover {
    	text-decoration: none;
    	background: #007ead;
    	background: -webkit-gradient(linear, left top, left bottom, from(#0095cc), to(#00678e));
    	background: -moz-linear-gradient(top,  #0095cc,  #00678e);
    }
    /* Fixes submit button height problem in Firefox */
    .tfbutton::-moz-focus-inner {
      border: 0;
    }
    .tfclear{
    	clear:both;
    }


  <div id="tfheader">
  <form id="tfnewsearch" method="post" action= /user_skills/search>
  <select id="tfselect" name="select">
  <option value="users">Users</option>
  <option value="skills">Skills</option>
  </select> 
 
  <input type="text" class="tftextinput" name="searchBy" size="21" maxlength="120">
  <input type="submit" id="button"  value="search" class="tfbutton">
  </form>
  <div class="tfclear"></div>
  </div>

app/views/user_skills/search_skill.html.haml
%p#notice= notice
%p
%center
  %font{:size => "5"}
    %strong
      = @skillSearch
= link_to 'Back', user_skills_path
%table{:style => "width:100%"}
  %tr
    %th
      %p
        %strong Skill
    %th
      %p
        %strong Competence
  - @searchedUsers.each do |user|
    %tr
      %td
        = User.find_by(id: user.user_id).name
      %td
        = user.competence

app/views/user_skills/search_skill_assessor.html.haml
%p
%center
  %font{:size => "5"}
    %strong
      = @skillSearch
= link_to 'Back', user_skills_path
%table{:style => "width:100%"}
  %tr
    %th
      %p
        %strong User
    %th
      %p
        %strong Competence
  - @searchedUsers.each do |user|
    %tr
      %td
        = User.find_by(id: user.user_id).name
      %td
        = user.competence

      %td
        -if current_user.has_role? :assessor, Skill.find(user.skill_id)
          %form#tfnewsearch{:action => "/user_skills/endorseskill?endorseUser=#{user.user_id}&endorseSkill=#{user.skill_id}", :method => "post"}
            %input#button{:type => "image", :height => "30", :src => "#{asset_path( 'endorse.gif' )}", :width => "30"}

  :css
    input[type="submit"] {

    background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;
    overflow: hidden;
    outline:none;
    width= 30;
    height= 30;
    }

app/views/user_skills/search_user.html.haml
%p#notice= notice
%p
%center
  %font{:size => "5"}
    %strong
      = @user.name
%table{:style => "width:100%"}
  %tr
    %th
      %p
        %strong Skill
    %th
      %p
        %strong Category
    %th
      %p
        %strong Competence
  - @skills.each do |skill|
    %tr
      %td
        = skill.name
      %td
        = skill.category
      %td
        = UserSkill.find_by(skill_id: skill.id , user_id: @user.id).competence
      %td
        -if current_user.has_role? :assessor, skill
          %form#tfnewsearch{:action => "/user_skills/endorseuser?endorseUser=#{@user.id}&endorseSkill=#{skill.id}", :method => "post"}
            %input#button{:type => "image", :height => "30", :src => "#{asset_path( 'endorse.gif' )}", :width => "30"}


  = link_to 'Back', user_skills_path 

app/views/user_skills/show.html.haml
%p
  %strong Competence:
  = @user_skill.competence
= link_to 'Edit', edit_user_skill_path(@user_skill)
|
= link_to 'Back', user_skills_path