config/routes.rb
Rails.application.routes.draw do
  resources :skills
  devise_for :users, module: "users"
  resources :skills
  resources :users do
    scope module: :users do
      resources :skills
    end
  end

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]

  root 'pages#index'

  get '*path' => redirect('/')

  post 'skills/search'
  post 'users/search'
  post 'skills/endorseskill'
  post 'users/endorseuser'
  
	

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  include Searchable

  has_many :user_skills, dependent: :destroy
  has_many :users, through: :user_skills
  resourcify
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /skills
  # GET /skills.json
  def index
    @search = params[:search]
    @skills = Skill.search(params[:search])
    
  end
  
  def search
  search_skill
  end 
  
  def endorseskill 
  
    @userskill=UserSkill.find_by(user_id: params[:endorseUser], skill_id: params[:endorseSkill])
    @target_user = User.find(params[:endorseUser])
    @target_skill = Skill.find(params[:endorseSkill])
    @competence=@userskill.competence
    @userskill.competence= @competence +1
    if @userskill.competence >= 5
        @target_user.add_role :assessor, @target_skill
    end
    @userskill.save
    refresh_search_skill
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to '/skills', notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to '/skills', notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :category, :search)
    end
    def search_skill
    @skillSearch= params[:search]
    @skillId=Skill.select("id").find_by name: params[:search]
    if @skillId
      @searchedUsers=UserSkill.where(skill_id: @skillId).select("user_id","skill_id","competence")
      render :action => :search_skill_assessor
    else
      respond_to do |format|
        format.html { redirect_to skills_path, notice: "Skill does not exist" }
        format.json { head :no_content }
      end
    end
  end

  def refresh_search_skill
    @skillId=params[:endorseSkill]
    @skillSearch= Skill.find(@skillId).name
    @searchedUsers=UserSkill.where(skill_id: @skillId).select("user_id","skill_id","competence")
    render :action => :search_skill_assessor
  end
end

app/controllers/users/skills_controller.rb
class Users::SkillsController < ApplicationController
  before_action :set_user_skill, only: [:show, :edit, :update, :destroy]
  before_action :skip_authorization

  # GET /user/skills
  # GET /user/skills.json
  def index
    @user_skills = current_user.skills
  end

  # GET /user/skills/1
  # GET /user/skills/1.json
  def show
  end

  # GET /user/skills/new
  def new
    @user_skill = UserSkill.new
  end

  # GET /user/skills/1/edit
  def edit
  end

  # POST /user/skills
  # POST /user/skills.json
  def create
      #byebug
    
    params[:user_skill][:user_id] = current_user.id if current_user
    @user_skill = UserSkill.new(user_skill_params)

    respond_to do |format|
      if @user_skill.save
        format.html { redirect_to current_user, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @user_skill }
      else
        format.html { render :new }
        format.json { render json: @useuser_skill_paramsr_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/skills/1
  # PATCH/PUT /user/skills/1.json
  def update
    respond_to do |format|
      if @user_skill.update(user_skill_params)
        format.html { redirect_to '/user_skuser_skill_paramsills', notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_skill }
      else
        format.html { render :edit }
        format.json { render json: @user_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/skills/1
  # DELETE /user/skills/1.json
  def destroy
    @user_skill.destroy
    respond_to do |format|
      format.html { redirect_to user_skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_skill
      @user_skill = current_user.skills.find(params[:user_skill][:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_skill_params
       
      accessible = [ :user_id, :skill_id, :id ] # extend with your own params
      params.fetch(:user_skill, {}).permit(accessible)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user/skills_helper.rb
module User::SkillsHelper
end

app/views/skills/_form.html.haml
= form_for(@skill) do |f|
  - if @skill.errors.any?
    #error_explanation
      %h2
        = pluralize(@skill.errors.count, "error")
        prohibited this skill from being saved:
      %ul
        - @skill.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :category
    %br/
    = f.text_field :category
  .actions
    = f.submit

app/views/skills/_skill.html.haml
%li{:id => "skill- skill.id"}
  %span.skill= skill.name

app/views/skills/_skills.html.haml
%table
  %thead
    %tr
      %th Name
      %th Category
      %th
  %tbody
    - @skills.each do |skill|
      %tr
        %td= link_to skill.name, skill
        %td= skill.category
        - if current_user.is_admin?
          %td= link_to 'Edit', edit_skill_path(skill)
          %td= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' }

app/views/skills/edit.html.haml
%h2 Editing Skill
= render 'form'
= link_to 'Show', @skill
|
= link_to 'Back', skills_path
  :css
    input[type="submit"] {

    background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;
    overflow: hidden;
    outline:none;
    width= 30;
    height= 30;
    }

    @import url(http://fonts.googleapis.com/css?family=Open+Sans:300,400,700);



    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #4DC3FA;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }

app/views/skills/index.html.haml
%h1 Listing Skills
= form_tag :controller => :skills, :action => :search, method: 'post' do
  = text_field_tag :search, params[:search]
  = submit_tag "Search", name: nil
%br/
.products 
  = render 'skills'
- if current_user.is_admin?
  = link_to 'New Skill', new_skill_path
  
  
  
  
  
:css


    @import url(http://fonts.googleapis.com/css?family=Open+Sans:300,400,700);



    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #FB667A;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }

app/views/skills/index.js.haml
$("#skills").html("<%= escape_javascript(render("skills")) %>");
$("#skills").show();

app/views/skills/new.html.haml
%h2 New Skill
= render 'form'
= link_to 'Back', skills_path
  :css
    input[type="submit"] {

    background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;
    overflow: hidden;
    outline:none;
    width= 30;
    height= 30;
    }

    @import url(http://fonts.googleapis.com/css?family=Open+Sans:300,400,700);



    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #4DC3FA;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }

app/views/skills/search_skill_assessor.html.haml
%p
%center
  %font{:size => "5"}
    %strong
      = @skillSearch
= link_to 'Back', skills_path
%table{:style => "width:100%"}
  %tr
    %th
      %p
        %strong User
    %th
      %p
        %strong Competence
  - @searchedUsers.each do |user|
    %tr
      %td
        = User.find_by(id: user.user_id).name
      %td
        = user.competence

      %td
        -if current_user.has_role? :assessor, Skill.find(user.skill_id)
          %form#tfnewsearch{:action => "/skills/endorseskill?endorseUser=#{user.user_id}&endorseSkill=#{user.skill_id}", :method => "post"}
            %input#button{:type => "image", :height => "30", :src => "#{asset_path( 'endorse.gif' )}", :width => "30"}

  :css
    input[type="submit"] {

    background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;
    overflow: hidden;
    outline:none;
    width= 30;
    height= 30;
    }

    @import url(http://fonts.googleapis.com/css?family=Open+Sans:300,400,700);



    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #4DC3FA;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }

app/views/skills/show.html.haml
%p
  %strong Name:
  = @skill.name
%p
  %strong Category:
  = @skill.category
= link_to 'Edit', edit_skill_path(@skill)
|
= link_to 'Back', skills_path


:css


    @import url(http://fonts.googleapis.com/css?family=Open+Sans:300,400,700);



    body {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color:#A7A1AE;
    background-color:#1F2739;
    }

    h1 {
    font-size:3em; 
    font-weight: 300;
    line-height:1em;
    text-align: center;
    color: #4DC3FA;
    }

    h2 {
    font-size:1em; 
    font-weight: 300;
    text-align: center;
    display: block;
    line-height:1em;
    padding-bottom: 2em;
    color: #FB667A;
    }

    h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
    }

    .blue { color: #185875; }
    .yellow { color: #FFF842; }

    .container th h1 {
            font-weight: bold;
            font-size: 1em;
    text-align: left;
    color: #185875;
    }

    .container td {
            font-weight: normal;
            font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
                    box-shadow: 0 2px 2px -2px #0E1119;
    }

    .container {
            text-align: left;
            overflow: hidden;
            width: 80%;
            margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
    }

    .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
    padding-left:2%;  
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
            background-color: #323C50;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
            background-color: #2C3446;
    }

    .container th {
            background-color: #1F2739;
    }

    .container td:first-child { color: #FB667A; }

    .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
                    box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;
    
    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);
    
    transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
    transition-timing-function: line;
    }

    @media (max-width: 800px) {
    .container td:nth-child(4),
    .container th:nth-child(4) { display: none; }
    }